import { Inter } from 'next/font/google';
import '@/css/main.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <title>Jonatan Valdiviezo</title>
      </head>
      <body
        style={{
          width: '100vw',
          margin: 0,
        }}
      >
        {children}
      </body>
    </html>
  );
}
